### ISSUE TITLE
Bot requires "Embed Links" permission, even when not used

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#10]
## Issue

- [x] I have checked for related issues.
- [ ] I have updated to the latest [TypicalBot version](https://github.com/typicalbot/typicalbot).

### Issue Type

- [x] Bug Report
- [ ] Feature Report

### Description

The bot asks for permission to embed links, even though the bot doesn't use an embed message (see attached screenshot). I would expect that the bot would not ask for permission unless it needs it to perform the requested action.
![image](https://user-images.githubusercontent.com/11968358/54729410-501ca700-4b51-11e9-9186-5ed3d310fdaf.png)

*Update 04/13/19*
The bot requires "Embed Links" permission, even when it's not being used.
![image](https://user-images.githubusercontent.com/11968358/56081910-f4ec7600-5dd7-11e9-8cda-fb9f06639620.png)
![image](https://user-images.githubusercontent.com/11968358/56081920-07ff4600-5dd8-11e9-8f4c-ab78196c487a.png)

**Comment by tjrgg** [comment]
The issue is now a bit worse. The bot now requires the "Embed Links" permission all the time, even when the bot doesn't always use this permission.

Updated title to reflect.

**Comment by nsylke** [comment]
Fixed as of commit https://github.com/typicalbot/typicalbot/commit/b2c26bd48458347b55338d95a55fbb9323acb7ac.
