### ISSUE TITLE
Database Migration, Remap and Audit

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#101]
### Description

Database Audit: Dec 21, 2019
Database Migration: TBA
Database Remap: TBA

RethinkDB has been "dead" for roughly two years, but they are slowly reviving the project. Unfortunately, RethinkDB eats a lot of memory causing us to restart the process daily, which also brings TypicalBot offline. 

Internally, we have been talking about switching over to a different database, more specifically MongoDB. 

My two cents: Although I love MongoDB, I think we should also consider moving to a relational database such as PostgreSQL. 

### Have You...?
- [X] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [X] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by Skillz4Killz** [comment]
Love this!

+1 to MongoDB

Couple notes on this:

1. Should weight the pros/cons between Mongo & PGSQL? What are TypicalBot's needs from a database? RDB and MDB are very similar so a transition will be quite easy. Going to PGSQL will basically require everyone to learn a new language(SQL).
2. MongoDB is actually a mix of Relational and NoSQL so its a great solution even if you wanted the benefits of a relational db. It takes the best parts of a relational db.

**Comment by nsylke** [comment]
@Skillz4Killz I'd prefer to have a set in stone schema for our data instead of being able to throw whatever data that we want in it and MongoDB doesn't provide any clear schema definition whereas PGSQL does.

**Comment by Skillz4Killz** [comment]
MongoDB doesnt require a schema but add Mongoose and you get a clear schema that you can clearly lay out. Mongoose also adds on a really cool query language that works great and similar to RDB style. You can restrict any changes/updates/creates to the database as per your schema. Furthermore, you can add resolvers and validators as well which makes it really nice. 

I hope I don't try and sell MongoDB too much it's just what I personally love and use. PGSQL is an amazing db as well. Both of them can do everything you want from it.

My advice would be to make the decision on what you believe is better for TB for the next 5-10 years.

**Comment by tjrgg** [comment]
I'm open to both options. Personally, I'd like to see support for both.

That being said, I do agree with @Skillz4Killz that we should figure out what our needs are and choose a database that best suits those needs. Need should take precedence over preference. 10 years might be a bit of stretch in terms of looking ahead, but we should certainly think more about the long-term over the short-term.
