### ISSUE TITLE
[4.x] Monorepo

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#125]
### Description

I'm not a fan with the approach to making this a monorepo for 4.x. Ref: [4328028](https://github.com/typicalbot/typicalbot/commit/43280285dc161cf315c95cd3845891164f6d315c)

If we're going to do our own library, I think the library should be a separate repository. I also think the framework could be it's own repository. TypicalBot, using those two things, could be it's own repository (with the cli). That's 3 repositories. If you want to get a bit fancy, TB's repository could be mono with the bot and cli separate, but I'd probably frown upon that, too.

Don't get me wrong, a monorepo makes sense for some projects, I just don't think this is one of those projects, even with a library and framework. It doesn't make sense to put them together in one repository, in my opinion.

### Usefulness

This "suggestion" is more just to document my complaint, but also to provide an opportunity for other contributors to have a discussion on the matter.

One of the reasons I disagree with a monorepo is that it adds unnecessary complexity to the project that new contributors might not understand, which I deeply frown upon.

### Have You...?
- [x] I have checked previous issues to see if my suggestion has already been suggested.
- [x] I have checked previous issues and pull requests to see if my suggestion has already been completed for an upcoming release.

**Comment by nsylke** [comment]
Will be splitting packages into multiple repositories.
