### ISSUE TITLE
Typo in settings command response

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#14]
## Issue

- [x] I have checked for related issues.
- [ ] I have updated to the latest [TypicalBot version](https://github.com/typicalbot/typicalbot).
- [x] I am using an official bot operated by TypicalBot.

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

When trying to edit a setting that doesn't exist, you get a message with an error. The screenshot below shows the error.
![image](https://user-images.githubusercontent.com/11968358/55603303-9ff19580-572f-11e9-8134-b3a8069be317.png)

I tried looking for where to change this and instead submit a PR, but couldn't find it. Maybe someone can enlighten me...

**Comment by nsylke** [comment]
Ah! It looks like the settings command was pushed to the live version of TypicalBot Beta on accident. I'll fix that locally and should push the settings command to the repository soon.

**Comment by nsylke** [comment]
This has been fixed as of commit https://github.com/typicalbot/typicalbot/commit/4b6ee6813dcd04f2d79c54134c909fcc06e04611.
