### ISSUE TITLE
Invite Command

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#17]
## Issue

- [x] I have checked for related issues.
- [x] I have updated to the latest [TypicalBot version](https://github.com/typicalbot/typicalbot).
- [ ] I am using an official bot operated by TypicalBot.

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

As it stands, the `invite` command for TypicalBot sends a link that redirects to the invite for the official TypicalBot. I believe this should be changed to dynamically form the invite link for the active client (using the client ID of the current client), instead of hardcoding TypicalBot's invite link.

**Comment by nsylke** [comment]
Implemented as of commit https://github.com/typicalbot/typicalbot/commit/8f6fc97792606136ccf1b959366ed933de555a43.
