### ISSUE TITLE
Autorole sync after restarting/outage

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#208]
### Description

After a restart/outage of TypicalBot, there may be users in communities without the proper roles. We should automatically pool these users and add the autorole(s). 

### Usefulness

Guarantees that all users in the community has the proper roles. 

### Have You...?
- [X] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [X] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
Uh, there's a problem with this idea. There's a possibility that there's an autorole that's given to users when they join, but is later removed (unverified members, for example). Automatically assuming a guild wants to re-add this role isn't a good solution.

**Comment by nsylke** [comment]
> Uh, there's a problem with this idea. There's a possibility that there's an autorole that's given to users when they join, but is later removed (unverified members, for example). Automatically assuming a guild wants to re-add this role isn't a good solution.

Unless you can provide an alternative solution to this, I don't see another way around making our system bullet-proof from outages/restarts.

**Comment by tjrgg** [comment]
@nsylke I can think of two alternatives. One is a command that essentially does what you're asking for here, but requires that the user expressly tells the bot this is the behavior they want. Two is a setting that controls this automated behavior (an option to turn it off).

I'd probably lean towards the setting and allowing the option to be turned off. I'm not opposed to this being the default behavior, but there needs to be a way for servers to opt-out of this behavior.

**Comment by nsylke** [comment]
Fixed in 7485ba99dad64cb8f3e68120170a371181339f34
