### ISSUE TITLE
Random User Selector

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#21]
## Issue

- [x] I have checked for related issues.
- [ ] I have updated to the latest [TypicalBot version](https://github.com/typicalbot/typicalbot).
- [ ] I am using an official bot operated by TypicalBot.

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

A command that selects a random user (perhaps based on conditionals, as suggested in issue #20). [Based on a question from `Chinmay#1003`.]

**Comment by TobiasFeld22** [comment]
Suggestion from Joel (Frink): 
"Possibly change the syntax of $randomuser to $randomuser [number of users to pick from]"

**Comment by tjrgg** [comment]
The `$randomuser` command has been implemented. As of now, the command doesn't take any arguments. However, if you feel it should, comment on #48.
