### ISSUE TITLE
Remove eval localization

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#305]
### Description

Remove translations for eval command

### Usefulness

As a system command, this doesn't need to be localized.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
I don't see any harm in localizing system commands and feel it should still be localized for anyone that might want to take this project and run it themselves. It also ensures consistency in that commands aren't treated differently.
