### ISSUE TITLE
Rename core category to generic

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#307]
### Description

Rename the core category to generic.

### Usefulness

A more suited name for the commands.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
I don't really like `generic`. I think `core` is fine.

**Comment by nsylke** [comment]
> I don't really like `generic`. I think `core` is fine.

`core` doesn't suit the commands. I would compromise for `general`.

**Comment by tjrgg** [comment]
> `core` doesn't suit the commands. I would compromise for `general`.

Alright, I can accept `general`.
