### ISSUE TITLE
`yomama` command not working

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#311]
### Description

yomama command doesn't work - api is offline

### Reproduction Steps

`$yomama`

### Observed Behavior

An error occurred making that request

### Expected Behavior

Yomama joke

### Additional Details

- Operating System: N/A
- TypicalBot Version: master

### Have You...?
- [x] I have checked for previous issues reporting this problem.
- [x] I have tried to reproduce this problem on the latest `master` commit.
- [x] I have tried to reproduce this problem on the official bot operated by TypicalBot.

**Comment by ayntee** [comment]
The API is working just fine, can't say that about the command.

**Comment by nsylke** [comment]
@ayntee Looks like command is working as well. A few of the external APIs break sometimes don't come back so we need to find a new one. However it looks like this API did come back.

The repository isn't dead, I haven't pushed any updates lately due to being busy at work and out of town.
