### ISSUE TITLE
conf command - settings successor

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#319]
### Description

Usage for the successor of `settings`:
 - `conf` will be short for `configure`
 - `conf [setting]` => view setting
 - `conf [setting] [value]` => edit setting

I would like us to see provide better configuration values, by mapping the value we put in the database and the one users can use to update the setting.

For example if the user types `true` for certain settings it returns with an error, but if the user types `enable` then it succeeds. To get started, here are some ideas for new aliases to `enable`:
 - true
 - 1
 - permit
 - approve

### Usefulness

Provides a better user experience.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
So long as `set` and `settings` are aliases to this new `conf` command, that's fine.

**Comment by nsylke** [comment]
> So long as `set` and `settings` are aliases to this new `conf` command, that's fine.

They will be aliases until 4.x.

**Comment by tjrgg** [comment]
> They will be aliases until 4.x.

Why until 4.x?
