### ISSUE TITLE
Command similarity

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#34]
## Issue

- [X] I have checked for related issues.
- [ ] I have updated to the latest [TypicalBot version](https://github.com/typicalbot/typicalbot).
- [ ] I am using an official bot operated by TypicalBot.

### Issue Type

- [ ] Bug Report
- [X] Feature Request

### Description

When making a mistake in command, check for similarity and prompt the user if they meant X instead Y. Maybe make it so it'll auto run the correct command?

**Comment by nsylke** [comment]
I'd like to say this feature does go against the [best practices for Discord bots](https://github.com/meew0/discord-bot-best-practices) (No. 6). If this becomes a permanent feature in TypicalBot, it'll either be a request-type feature or locked for TypicalBot Prime users.

**Comment by tjrgg** [comment]
`.... If your bot's prefix is configurable, this rule can probably be safely disregarded.`
That rule doesn't apply for TypicalBot since its prefix is configurable. Regardless, I think it would be acceptable to make this a configurable option.

**Comment by nsylke** [comment]
> 
> 
> `.... If your bot's prefix is configurable, this rule can probably be safely disregarded.`
> That rule doesn't apply for TypicalBot since its prefix is configurable. Regardless, I think it would be acceptable to make this a configurable option.

Fair enough. I'd like to do further testing and measure the performance. Assuming it's not expensive to call the method we may open it everyone, or just make it request access (instead of limiting to just TypicalBot Prime.)

**Comment by nsylke** [comment]
Implemented as of commit https://github.com/typicalbot/typicalbot/commit/40c53a873b125b59f895fc706b0ca31ac92ceb43.
