### ISSUE TITLE
Voicekick Command

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#35]
## Issue

- [x] I have checked for related issues.
- [ ] I have updated to the latest [TypicalBot version](https://github.com/typicalbot/typicalbot).
- [ ] I am using an official bot operated by TypicalBot.

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

A `voicekick` command that kicks a member from the voice channel they're in.

**Comment by nsylke** [comment]
This has already been implemented.
