### ISSUE TITLE
Contribution guide refers to nonexistent changelog

### ISSUE THREAD

**Issue by SpecLad** [typicalbot/typicalbot#368]
### Description

The contribution guide has a [CHANGELOG](https://github.com/typicalbot/typicalbot/blob/7890aba/.github/CONTRIBUTING.md#changelog) section that describes how to maintain the `CHANGELOG` file. However, no such file actually exists in the repository.

(I took the liberty of removing the rest of the issue template, since it's not really applicable for an issue like this one.)

**Comment by tjrgg** [comment]
Seems the Contributing Guide is a bit out of date. We'll get that updated.

**Comment by nsylke** [comment]
Removed in c1e1ebf
