### ISSUE TITLE
Mass assign/unassign roles

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#51]
### Description

Allow to mass assign/unassign roles from users (Suggested by `UserID10T#2790`.) This is related to #20 except that it was suggested to not use a subcommand. 

### Have You...?
- [X] I have checked for related issues.
- [X] I have checked the documentation to ensure my idea or suggestion doesn't already exist.

**Comment by tjrgg** [comment]
Commented on issue #20.
