### ISSUE TITLE
'$set view' does not return current setting values

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#52]
### Description

When doing `$set view`, TypicalBot returns "Currently Set Settings:" with no settings listed.

### Reproduction Steps

1. Do `$set view`.
2. Read response.

### Observed Behavior

The output is `**__Currently Set Settings:__**`.

### Expected Behavior

I expected to see a list of settings and their current values.

### Additional Details

- Operating System: Ubuntu 18.04
- TypicalBot Version: 2.4.1

### Have You...?
- [x] I have checked for previous issues reporting this problem.
- [x] I have tried to reproduce this problem on the latest `master` commit.
- [x] I have tried to reproduce this problem on the official bot operated by TypicalBot.

**Comment by ShivamRawat0l** [comment]
Can I try fixing this issue ?

**Comment by tjrgg** [comment]
@ShivamRawat0l You're welcome to submit a pull request.

**Comment by Skillz4Killz** [comment]
This was patched in #78 
![image](https://user-images.githubusercontent.com/23035000/67116531-93ee9200-f1ae-11e9-9dba-3ba1778760bb.png)

**Comment by nsylke** [comment]
@Skillz4Killz I think the idea was to display all current **set** settings.

**Comment by Skillz4Killz** [comment]
Apologies for the misunderstanding. Modified it so it is as below:

![image](https://user-images.githubusercontent.com/23035000/67121036-8ccc8180-f1b8-11e9-9715-8a512ef0de45.png)

![image](https://user-images.githubusercontent.com/23035000/67121044-90f89f00-f1b8-11e9-8fcb-86952f8a8928.png)

![image](https://user-images.githubusercontent.com/23035000/67121056-981fad00-f1b8-11e9-98c7-53fe75493410.png)
