### ISSUE TITLE
Running without Cluster Manager

### ISSUE THREAD

**Issue by HyperCoder2975** [typicalbot/typicalbot#57]
### Description

The bot currently doesn't run properly without using the cluster manager.

### Usefulness

This would allow contributors and self-hosting users to run the bot without the cluster manager running.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
#94 closes this issue.
