### ISSUE TITLE
Refactor Configuration

### ISSUE THREAD

**Issue by HyperCoder2975** [typicalbot/typicalbot#58]
### Description

Changing the configuration file from JSON to env.

### Usefulness

It provides an easier way to retrieve configuration.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by Skillz4Killz** [comment]
A JSON file does provide nice clean automated typings for TS. An env file will not provide the same. I think a JSON file is pretty simple to use and is a good way to keep configs.

**Comment by nsylke** [comment]
I personally don't feel like we should change to an .env configuration file. If you anything, pass the environment variables through the command line.
