### ISSUE TITLE
Implement Airbnb JavaScript Style Guide

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#67]
### Description

In 3.0.0, it would be great if all contributors followed the same style guide when developing new commands and features. In our [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md), we adopted the Airbnb JavaScript Style Guide. I aim to move forward with implementing that style guide in our source code for the release of 3.0.0.

### Usefulness

Implementing the style guide will allow all contributors to be working on familiar code while keeping everything consistent.

### Progress

Progress on this issue is being made in the [`3.0.0-beta`](https://github.com/typicalbot/typicalbot/tree/3.0.0-beta) branch. The following directories have been fully linted and all problems corrected in order to comply with the Airbnb JavaScript Style Guide.

- [ ] scripts
- [ ] src
  - [ ] commands
  - [ ] events
  - [ ] functions
  - [ ] handlers
  - [ ] lib
  - [ ] permissions
  - [ ] structures
  - [ ] tasks
  - [ ] util

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by Skillz4Killz** [comment]
Is this still desired? In #78 it was set to using eslint-config-typicalbot as the custom eslint settings for all typicalbot projects.

**Comment by tjrgg** [comment]
Yes, this is still desired. This issue is about ensuring each file doesn't have any lint problems and that everything complies with the lint rules. Last time I checked, this wasn't the case.
