### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/typicalbot#77]
### Description

I'd like to propose that we adopt a set of rules that govern the TypicalBot organization.

As our project grows and more people engage with our community, it'll become increasing important to ensure that everyone has an understanding of what our expectations are as a community and how the community functions. We currently have our [Code of Conduct](https://github.com/typicalbot/typicalbot/blob/master/.github/CODE_OF_CONDUCT.md), which governs the conduct of everyone that participates in our organization. However, we don't have a governing document that governs the manner and rules in which the organization should operate. These are the kinds of rules I think we should adopt, since without these rules, decisions are made freely without much discussion and sometimes, without regard to the potential consequences.

To formally adopt some governance and establish a structure for our organization, I think we should write some rules and publish them in a GOVERNANCE.md file in our repositories. For example, the [Material-UI](https://github.com/mui-org) organization has their governance rules in a [GOVERANCE.md](https://github.com/mui-org/material-ui/blob/master/docs/src/pages/discover-more/governance/governance.md) file.

Before we do that, I want to take an opportunity to hear from the community and our current contributors to decide how these rules, if any, should look, and what questions they should answer. I've added a couple of questions I think are important for any governance rules to answer, but I'll add more as they come up as well as suggestions on how to address them.

#### Questions
The following is a list of questions that governance rules should answer:

- [ ] What are the roles and responsibilities of members of the TypicalBot organization?
- [ ] What are the roles and responsibilities of contributors to TypicalBot repositories?
- [ ] How are decisions made at the organization level?
- [ ] How are decisions made at the repository level?

### Usefulness

Adopting a Governance will allow us to be better organized and help us maintain and make decisions for our projects more easily in the future.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by TobiasFeld22** [comment]
Could you update the link to the governance.md file / a similair file?

**Comment by tjrgg** [comment]
Link updated.

**Comment by nsylke** [comment]
Although this was my idea, I don't see a need for this anymore. Thus I will be closing the issue, if we decide to reconsider this in the future, then we can create a new issue.
