### ISSUE TITLE
Use Redis to store Music Data

### ISSUE THREAD

**Issue by HyperCoder2975** [typicalbot/typicalbot#80]
### Description

Use a redis database to store music data in the case that TypicalBot restarts, it will reload all of the queues and songs being played by each server.

### Usefulness

This will prevent users from needing to re-queue their music after a restart.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by nsylke** [comment]
Will be closing this as we have decided to deprecate music functionality.
