### ISSUE TITLE
Unable to check custom status for ads

### ISSUE THREAD

**Issue by nsylke** [typicalbot/typicalbot#91]
### Description

The `$adcheck` command is unable to read custom statuses, allowing users to bypass the system. 

### Reproduction Steps

Change your custom status to `discord.gg/typicalbot` and run `$adcheck`

### Observed Behavior

No users with an invite in status.

### Expected Behavior

X user has invite in status. 

### Additional Details

- Operating System: ubuntu 16.04
- TypicalBot Version: master

### Have You...?
- [X] I have checked for previous issues reporting this problem.
- [X] I have tried to reproduce this problem on the latest `master` commit.
- [X] I have tried to reproduce this problem on the official bot operated by TypicalBot.

**Comment by tjrgg** [comment]
This isn't really a bug, it's just something that's not yet supported. There will likely be an update to discord.js soon that will fix this issue. See discordjs/discord.js#3353.

**Comment by nsylke** [comment]
Will this PR change the syntax of the variables/methods required to producing the expected behavior?

**Comment by nsylke** [comment]
This has been fixed.
